import { Router, Request, Response } from 'express';
import { storage } from '../services/storageService';

export const reportRouter = Router();

reportRouter.get('/:interviewId', (req: Request, res: Response): void => {
  const interview = storage.getInterview(req.params.interviewId);
  if (!interview) {
    res.status(404).json({ error: 'Interview not found' });
    return;
  }

  const { aiResult, title, uploadedAt, fileName } = interview;
  if (!aiResult) {
    res.status(400).json({ error: 'No AI analysis available. Run analysis first.' });
    return;
  }

  res.json({
    title,
    fileName,
    uploadedAt,
    generatedAt: new Date().toISOString(),
    summary: aiResult.summary,
    keyQuotes: aiResult.keyQuotes,
    painPoints: aiResult.painPoints,
    mainThemes: aiResult.mainThemes,
    clusters: aiResult.clusters
  });
});

reportRouter.get('/:interviewId/markdown', (req: Request, res: Response): void => {
  const interview = storage.getInterview(req.params.interviewId);
  if (!interview) {
    res.status(404).json({ error: 'Interview not found' });
    return;
  }

  const { aiResult, title, uploadedAt } = interview;
  if (!aiResult) {
    res.status(400).json({ error: 'No AI analysis available' });
    return;
  }

  const dateStr = new Date(uploadedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  });

  const md = `# UX Research Report: ${title}

**Interview Date:** ${dateStr}
**Report Generated:** ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

---

## Executive Summary

${aiResult.summary}

---

## Key Quotes

${aiResult.keyQuotes.map(q => `> ${q}`).join('\n\n')}

---

## Pain Points

${aiResult.painPoints.map((p, i) => `${i + 1}. ${p}`).join('\n')}

---

## Main Themes

${aiResult.mainThemes.map(t => `- **${t}**`).join('\n')}

---

## Affinity Clusters

${aiResult.clusters.map(c => `### ${c.name}\n\n${c.description}\n\n**Related Themes:** ${c.themes.join(', ')}`).join('\n\n')}

---

*Report generated by AI UX Research Copilot*
`;

  res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="${title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-report.md"`
  );
  res.send(md);
});
